services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: se_user
      POSTGRES_PASSWORD: test
      POSTGRES_DB: dev_db
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5